config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'stats' => 'home#stats'
  post 'short' => 'home#short'
  # -----------
  get "/:code" => "home#page_redirect"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track_url.rb
class TrackUrl < ApplicationRecord
	validates_presence_of :redirect_url
	validates_format_of :redirect_url, with: /https?:\/\/[\S]+/, message: "Invalid URL, Must contain http."

	scope :valid, -> {where("date(created_at) > ?", 1.month.ago)}

	def is_active?
		(created_at + 30.days) > Time.now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "password", only: [:stats]

  def index
  end

  def stats
  	@track_urls = TrackUrl.order("created_at desc").paginate(page: params[:page], per_page: 7)
  end

  def short
  	ip = request.remote_ip
  	country = Geocoder.search(ip).first.country
		url = SecureRandom.alphanumeric(5)
  	@track_url = TrackUrl.new(url: url, redirect_url: params[:redirect_url], ip_address: ip, country: country)
  	@track_url.save
  end

  def page_redirect
  	@track_url = TrackUrl.valid.where(url: params[:code]).last
  	if @track_url
  		@track_url.increment!(:clicks)
  		redirect_to @track_url.redirect_url
  	else
  		render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 class="w3-container w3-green">Welcome to URL Shortener</h1>
<%= form_tag(short_path, method: 'post', remote: true, class: "form" ) do %>
  <%= label_tag(:redirect_url, 'Please enter your Redirect link:') %>
  <br>
  <%= text_field_tag(:redirect_url, nil, required: true, class: "form-input w3-input", placeholder: "URL here") %>
  <br>
  <br>
  <%= submit_tag("SHORTEN", class: "bg-color-orange w3-button") %>
<% end %>
<div id="error"></div>
<div id="results"></div>

app/views/home/short.js.erb
<% if @track_url.errors.any? %>
	$("#results").html("")
	$("#error").html("<ul><% @track_url.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul>")
<% else %>
	$("#url").val("")
	$("#error").html("")
	$("#results").html('<p class="">Here is your short url.</p><h4 id="copy_link" ><%=root_url + @track_url.url%></h4><div class="cpy-btn bg-color-orange c-pointer" onclick="copyToClipboard()">COPY URL!</div>')
<% end %>

function copyToClipboard() {
  var $temp = $("<input>");
  $("body").append($temp);
  $temp.val($('#copy_link').html()).select();
  document.execCommand("copy");
  $temp.remove();
  alert("Url copied successfully!")
}

app/views/home/stats.html.erb
<div class="container">
	<h2>Analytics | <%= link_to "home", "/"%></h2>
	<% @track_urls.each do |tu| %>
			<div class="list-redirect_url w3-gray"><%= tu.redirect_url %></div>
			<div class="list-url"><%= root_url + tu.url %></div>
			<div class="list">Total Clicks - <%= tu.clicks %></div>
			<div class="list">Top countries - <%= tu.country %></div>
			<div class="list">Status - <%= tu.is_active? ? "Active" : "In-active" %></div>
			<hr>
	<% end %>
	<%= will_paginate @track_urls %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shortener</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>